### ISSUE TITLE
[@bara/core] feat: implement useStream

### ISSUE THREAD

**Issue by nampdn** [barajs/bara#11]
- [x] Register using pure function
- [x] Prevent useStream of duplication name

**Comment by locndv** [comment]
- Duplicate stream
![Screen Shot 2019-04-11 at 5 25 52 PM](https://user-images.githubusercontent.com/42598289/55950365-f3f40100-5c7e-11e9-81e8-bd35a9a9cd23.png)

**Comment by nampdn** [comment]
> * Duplicate stream
>   ![Screen Shot 2019-04-11 at 5 25 52 PM](https://user-images.githubusercontent.com/42598289/55950365-f3f40100-5c7e-11e9-81e8-bd35a9a9cd23.png)

This has been fixed in #18
